### ISSUE TITLE
Fix --protocolversion 59 to 60 

### ISSUE THREAD

**Issue by wooomp** [AugurProject/augur-client#69]
Fix --protocolversion 59 to 60 

blog article for setup in section 4 states 59, which provides error, set to 60 works.

**Comment by joeykrug** [comment]
Protocolversion is supposed to be 59 so you don't get stuck on regular testnet --- if you use 60 there's a decent chance you'll overwrite all our blocks w/ testnet blocks due to a geth bug.  If you can't connect to peers, try connecting to some of the ones listed in the blog post using admin.addPeer in geth

**Comment by wooomp** [comment]
I stopped running on 60
FYI - When I try to run it at 59 I get   - Fatal: Database version mismatch. Protocol (60 / 59). 'rm -rf C:\users\......\roaming\ehterium\blockchain

**Comment by joeykrug** [comment]
ok so when you run on 59, since you previously ran on 60 you need to run in a new datadir folder, so as one of the parameters to geth in the command line do --datadir some_random_folder_you_created
