### ISSUE TITLE
trading fee errors

### ISSUE THREAD

**Issue by Sput** [AugurProject/augur-client#70]
I was able to create a market with a fee of .000000000000000000000000001% it shows up on the marketplace as fee 0%. Should there be a lower bound for how small a trading fee can be? Also was able to create a market with a trading fee of 200%. Both were briefly loaded to the markets page before being deleted (< 10 seconds).

**Comment by joeykrug** [comment]
Nice, so this is a UI bug.  The reason it got deleted was because it was an invalid market (the backend code checks for this stuff).  The UI shouldn't allow fees to be created that are out of the valid range though:

Currently for root branch min fee is .7% and global max is 12.5%

Branch min fee is defined as 
`BRANCHES.getMinTradingFee(branch)`

Global max fee is 2^61 or 12.5%
