### ISSUE TITLE
Firefox loads _all_ markets, keeps a purple loading screen, then appears

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-client#83]
Seems there's a firefox bug where it won't async load markets like on chrome.  Shows augur loading screen, loads all markets, then ui appears.

**Comment by scottzer0** [comment]
this is a side-effect of how the browser is reading the DOM due to the current heavy initial RPC load.  they behave slightly differently.  there's are solutions to trying to keep this consistent, but i would prefer to focus on reducing that load and having more, ultimate control again.

closing this.
